apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-pv-2
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
    - 10.0.169.87:6789
    path: /elasticsearch_node2
    user: admin
    secretRef:
      name: ceph-secret
